AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  Env:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - prod
    Description: "Specify the environment: dev or prod"

Resources:

  CognitoUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: !Sub "ClaimVisionUserPool-${Env}"
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireUppercase: true
          RequireLowercase: true
          RequireNumbers: true
          RequireSymbols: false
      AutoVerifiedAttributes:
        - email
      Schema:
        - Name: household_id
          AttributeDataType: String  # Store as a String
          Mutable: true
          Required: false
          DeveloperOnlyAttribute: false
      # Removing the Lambda configuration to eliminate circular dependency
      # and rely on the update_cognito_attributes function instead

  # Cognito App Client
  CognitoUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    DependsOn: CognitoUserPool
    Properties:
      ClientName: !Sub "ClaimVisionClient-${Env}"
      UserPoolId: !Ref CognitoUserPool
      GenerateSecret: false
      ExplicitAuthFlows:
        - ALLOW_USER_PASSWORD_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH
        - ALLOW_CUSTOM_AUTH
      AllowedOAuthFlows:
        - implicit
      AllowedOAuthScopes:
        - email
        - openid
        - profile
      CallbackURLs:
        - "http://localhost:3000"
      LogoutURLs:
        - "http://localhost:3000"
      WriteAttributes:
        - email
        - custom:household_id
      ReadAttributes:
        - email
        - custom:household_id
Outputs:
  CognitoUserPoolId:
    Description: "Cognito User Pool ID"
    Value: !Ref CognitoUserPool
    Export:
      Name: !Sub "CognitoUserPoolId-${Env}"

  CognitoUserPoolClientId:
    Description: "Cognito User Pool Client ID"
    Value: !Ref CognitoUserPoolClient
    Export:
      Name: !Sub "CognitoUserPoolClientId-${Env}"
