version = 0.1
[default.deploy.parameters]
stack_name = ""
resolve_s3 = 
s3_prefix = ""
region = ""
confirm_changeset = false
capabilities = ""
image_repositories = []
parameter_overrides = [
  "Env=dev",
  "S3BucketNameSSMPath=",
  "S3BucketName=",
  "CognitoUserPoolId=",
  "RDSEndpointSSMPath=",
  "DBUsernameSSMPath=",
  "DBPasswordSSMPath=",
  "DBUsername=",
  "DBPassword=",
  "DBEndpoint=",
  "FileUploadQueueURL=",
  "FileUploadQueueARN=",
  "FileUploadQueueName=",
  "FileAnalysisQueueURL=",
  "FileAnalysisQueueARN=",
  "FileAnalysisQueueName=",
  "UserRegistrationQueueURL=",
  "UserRegistrationQueueARN=",
  "UserRegistrationQueueName=",
  "CognitoUpdateQueueURL=",
  "CognitoUpdateQueueARN=",
  "CognitoUpdateQueueName=",
  "VpcId=",
  "SubnetIds=",
  "SecurityGroupIds=",
  "EnableDNS=true",
  "HostedZoneId=",
  "ApiDomainName=",
  "FrontendOrigin=",
  "EFSAccessPointARN=",
  "EFSFileSystemId=",
  "RdsSecurityGroupId=",
  "FileOrganizationQueueURL=",
  "FileOrganizationQueueARN=",
  "ReportRequestQueueURL=",
  "ReportRequestQueueARN=",
  "ReportsBucketName=",
  "DBPasswordSSMPath=",
  "DBUsernameSSMPath=",
  "PublicSubnet1=",
  "PublicSubnet2=",
  "SenderEmail=",
  "FileOrganizationQueueName=",
  "ReportRequestQueueName=",
  "DeliverReportQueueARN=",
  "DeliverReportQueueURL=",
  "EmailQueueURL=",
  "EmailQueueARN=",
  "EmailQueueName=",
  "S3UploadNotificationQueueARN=",
  "S3UploadNotificationQueueURL=",
]

[cognito.deploy.parameters]
stack_name = "ClaimVision-cognito-dev"
template_file = "cognito-template.yaml"