version = 0.1
[default.deploy.parameters]
stack_name = "ClaimVision-dev"
resolve_s3 = true
s3_prefix = "ClaimVision"
region = "us-east-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
image_repositories = []
parameter_overrides = [
  "Env=dev",
  "S3BucketNameSSMPath=/terraform/s3/bucket_name",
  "S3BucketName={{S3_BUCKET_NAME}}",
  "CognitoUserPoolId={{USER_POOL_ID}}",
  "RDSEndpointSSMPath={{RDS_ENDPOINT_SSM_PATH}}",
  "DBUsernameSSMPath={{DB_USERNAME_SSM_PATH}}",
  "DBPasswordSSMPath={{DB_PASSWORD_SSM_PATH}}",
  "DBUsername={{DB_USERNAME}}",
  "DBPassword={{DB_PASSWORD}}",
  "DBEndpoint={{DB_ENDPOINT}}",
  "FileUploadQueueURL={{FILE_UPLOAD_QUEUE_URL}}",
  "FileUploadQueueARN={{FILE_UPLOAD_QUEUE_ARN}}",
  "FileUploadQueueName={{FILE_UPLOAD_QUEUE_NAME}}",
  "FileAnalysisQueueURL={{FILE_ANALYSIS_QUEUE_URL}}",
  "FileAnalysisQueueARN={{FILE_ANALYSIS_QUEUE_ARN}}",
  "FileAnalysisQueueName={{FILE_ANALYSIS_QUEUE_NAME}}",
  "UserRegistrationQueueURL={{USER_REGISTRATION_QUEUE_URL}}",
  "UserRegistrationQueueARN={{USER_REGISTRATION_QUEUE_ARN}}",
  "UserRegistrationQueueName={{USER_REGISTRATION_QUEUE_NAME}}",
  "CognitoUpdateQueueURL={{COGNITO_UPDATE_QUEUE_URL}}",
  "CognitoUpdateQueueARN={{COGNITO_UPDATE_QUEUE_ARN}}",
  "CognitoUpdateQueueName={{COGNITO_UPDATE_QUEUE_NAME}}",
  "VpcId={{VPC_ID}}",
  "SubnetIds={{SUBNET_IDS}}",
  "SecurityGroupIds={{SECURITY_GROUP_IDS}}",
  "EnableDNS=true",
  "HostedZoneId={{HOSTED_ZONE_ID}}",
  "ApiDomainName={{API_DOMAIN_NAME}}",
  "FrontendOrigin={{FRONTEND_ORIGIN}}",
  "EFSAccessPointARN={{EFS_ACCESS_POINT_ARN}}",
  "EFSFileSystemId={{EFS_FILE_SYSTEM_ID}}",
  "RdsSecurityGroupId={{SECURITY_GROUP_IDS}}",
  "FileOrganizationQueueURL={{FILE_ORGANIZATION_QUEUE_URL}}",
  "FileOrganizationQueueARN={{FILE_ORGANIZATION_QUEUE_ARN}}",
  "ReportRequestQueueURL={{REPORT_REQUEST_QUEUE_URL}}",
  "ReportRequestQueueARN={{REPORT_REQUEST_QUEUE_ARN}}",
  "ReportsBucketName={{REPORTS_BUCKET_NAME}}",
  "PublicSubnet1={{PUBLIC_SUBNET_1}}",
  "PublicSubnet2={{PUBLIC_SUBNET_2}}",
  "SenderEmail={{SENDER_EMAIL}}",
  "FileOrganizationQueueName={{FILE_ORGANIZATION_QUEUE_NAME}}",
  "ReportRequestQueueName={{REPORT_REQUEST_QUEUE_NAME}}",
  "DeliverReportQueueARN={{DELIVER_REPORT_QUEUE_ARN}}",
  "DeliverReportQueueURL={{DELIVER_REPORT_QUEUE_URL}}",
  "EmailQueueURL={{EMAIL_QUEUE_URL}}",
  "EmailQueueARN={{EMAIL_QUEUE_ARN}}",
  "EmailQueueName={{EMAIL_QUEUE_NAME}}",
  "S3UploadNotificationQueueARN={{S3_UPLOAD_NOTIFICATION_QUEUE_ARN}}",
  "S3UploadNotificationQueueURL={{S3_UPLOAD_NOTIFICATION_QUEUE_URL}}",
]

[cognito.deploy.parameters]
stack_name = "ClaimVision-cognito-dev"
template_file = "cognito-template.yaml"