version = 0.1
[default.deploy.parameters]
stack_name = ""
resolve_s3 = 
s3_prefix = ""
region = ""
confirm_changeset = false
capabilities = ""
image_repositories = []
parameter_overrides = [
  "Env=dev",
  "S3BucketNameSSMPath=",
  "S3BucketName=",
  "CognitoUserPoolId=",
  "RDSEndpointSSMPath=",
  "DBEndpoint=",
  "FileUploadQueueURL=",
  "FileUploadQueueARN=",
  "FileUploadQueueName=",
  "FileAnalysisQueueURL=",
  "FileAnalysisQueueARN=",
  "FileAnalysisQueueName=",
  "UserRegistrationQueueURL=",
  "UserRegistrationQueueARN=",
  "UserRegistrationQueueName=",
  "CognitoUpdateQueueURL=",
  "CognitoUpdateQueueARN=",
  "CognitoUpdateQueueName=",
  "VpcId=",
  "EnableDNS=true",
  "HostedZoneId=",
  "ApiDomainName=",
  "FrontendOrigin="
]