AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  Env:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - prod
    Description: 'Specify the environment: dev or prod'

Conditions:
  IsDev: !Equals [!Ref Env, "dev"]

Globals:
  Function:
    Timeout: 10
    MemorySize: 128
    Runtime: python3.12
    Environment:
      Variables:
        COGNITO_USER_POOL_CLIENT_ID: !ImportValue CognitoUserPoolClientId-${Env}
        COGNITO_USER_POOL_ID: !ImportValue CognitoUserPoolId-${Env}

Resources:
  # API Gateway (Now Includes Cognito Authorizer)
  ClaimVisionAPI:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Sub ClaimVisionAPI-${Env}
      StageName: dev
      Cors:
        AllowMethods: '''OPTIONS,POST,GET'''
        AllowHeaders: '''Content-Type,Authorization'''
        AllowOrigin: '''*'''
      Auth:
        Authorizers:
          CognitoAuthorizer:
            UserPoolArn: !Sub "arn:aws:cognito-idp:${AWS::Region}:${AWS::AccountId}:userpool/${!ImportValue CognitoUserPoolId-${Env}}"

  LoginFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: auth.login.lambda_handler
      Runtime: python3.12
      CodeUri: src/
      Policies:
        - AWSLambdaBasicExecutionRole
      Events:
        LoginAPI:
          Type: Api
          Properties:
            Path: /auth/login
            Method: POST
            RestApiId: !Ref ClaimVisionAPI # No Auth here!


  RegisterFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: auth.register.lambda_handler
      Runtime: python3.12
      CodeUri: src/
      Policies:
        - AWSLambdaBasicExecutionRole
      Events:
        RegisterAPI:
          Type: Api
          Properties:
            Path: /auth/register
            Method: POST
            RestApiId: !Ref ClaimVisionAPI 

  ConfirmFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: auth.confirm.lambda_handler
      Runtime: python3.12
      CodeUri: src/
      Policies:
        - AWSLambdaBasicExecutionRole
      Events:
        ConfirmAPI:
          Type: Api
          Properties:
            Path: /auth/confirm
            Method: POST
            RestApiId: !Ref ClaimVisionAPI
  
  ResendConfirmationFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: auth.resend_confirmation.lambda_handler
      Runtime: python3.12
      CodeUri: src/
      Policies:
        - AWSLambdaBasicExecutionRole
      Events:
        ResendConfirmationAPI:
          Type: Api
          Properties:
            Path: /auth/resend-confirmation
            Method: POST
            RestApiId: !Ref ClaimVisionAPI

    PreSignUpFunction:
    Type: AWS::Serverless::Function
    Condition: IsDev
    Properties:
      Handler: auth.pre_signup.lambda_handler
      Runtime: python3.12
      CodeUri: src/
      Policies:
        - AWSLambdaBasicExecutionRole


  # Secure API Route (/items) with Cognito Authorizer
  GetItemsFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: items.get_items.lambda_handler
      Runtime: python3.12
      CodeUri: src/
      Policies:
        - AWSLambdaBasicExecutionRole
      Events:
        GetItemsAPI:
          Type: Api
          Properties:
            Path: /items
            Method: GET
            RestApiId: !Ref ClaimVisionAPI
            Auth:
              Authorizer: CognitoAuthorizer

Outputs:
  #  Print API Gateway URL After Deployment
  ApiGatewayInvokeURL:
    Description: API Gateway Invoke URL
    Value: !Sub https://${ClaimVisionAPI}.execute-api.${AWS::Region}.amazonaws.com/dev